apiVersion: v1
kind: Service
metadata:
  name: demoappv11
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoappv11
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoappv11
spec:
        #  replicas: 2
  selector:
    matchLabels:
      app: demoappv11
  template:
    metadata:
      labels:
        app: demoappv11
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      containers:
      - name: demoappv11
        image: ikubernetes/demoapp:v1.1
        ports:
        - containerPort: 80